Create database customer_behaviour_analysis;
Use customer_behaviour_analysis;

SELECT * FROM customer;

-- Business Insights Queastion

-- 1. Which products category generate Highest_revenue ?
SELECT category, ROUND(SUM(purchase_amount),2) AS highest_revenue FROM customer
GROUP BY category 
ORDER BY highest_revenue DESC;

-- Business Problem :- Company does not know which category generate highest revenue
-- Impact :- Helps to pripritize high-performing categories
		  -- Optimizes inventory planning
          -- Improves marketing Return on Investment
          
-- 2. Discounts actually increasing purchase value ? 

SELECT discount_applied, 
ROUND(SUM(purchase_amount),2) AS total_revenue,
ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer
GROUP BY discount_applied;

-- Buisness Problem : Discounts may reduce profit without increasing sales.
-- Impact :- Identify effectiveness of discounts
		-- Reduce unnecessary discount cost
        -- Improve Profit margins

-- 3. What is the total revenue generated by Gender ? 

SELECT gender, ROUND(SUM(purchase_amount),2) AS Total_revenue FROM customer
GROUP BY gender 
ORDER BY Total_revenue DESC;

-- Business Problem : Lack of understanding of revenue contribution?
-- Impact :- Helps design targated marketing campaign
		  -- Improves customer segmentation stratergy
          -- Enhances personalization efforts
          
-- 4. Which customer used a discount but still spent more than the average purchase amount ?

SELECT customer_id, purchase_amount, discount_applied
FROM customer
WHERE discount_applied = 'Yes' AND 
purchase_amount > (SELECT AVG(purchase_amount) 
FROM customer) LIMIT 10;

-- Business Problem :
-- Company cannot identify high-spending customers who are also diacount users.

-- Impact : Identifies premium discount-sensitive customers
		 -- Enabes targeted discount campaigns
         -- Improves customer retention and revenue

-- 5. Which are the Top/Bottom 5 products with the highest average review rating ? 

-- Top 5
SELECT Item_purchased,
ROUND(AVG(review_rating),2) AS Avg_Rating FROM customer
GROUP BY Item_purchased
ORDER BY Avg_Rating DESC LIMIT 5;

-- Bottom 5
SELECT Item_purchased,
ROUND(AVG(review_rating),2) AS Avg_Rating FROM customer
GROUP BY Item_purchased
ORDER BY Avg_Rating ASC LIMIT 5;

-- Business Problem : No visibility into product performace on customer satisfaction

-- Impact : Promotes high-performing products
		 -- Improves low-rated products
         -- Enhances customer exprience

-- 6. Average purchase : Standard vs Express shipping

SELECT shipping_type,
COUNT(DISTINCT customer_id) AS orders_placed,
ROUND(AVG(purchase_amount),2) AS avg_purchase,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer 
WHERE shipping_type IN('Standard', 'Express')
GROUP BY shipping_type
ORDER BY total_revenue DESC;

-- Business Problem : Unclear if faster shipping leads to higher spending.

-- Impact : Helps optimize shipping pricing strategy
		 -- Encourages premium shipping adoption
         -- Increses average order value 
         
-- 7. Do subscribed customers spend more ? 
-- Compare average speed and total revenue between subscribers and non-subscribers ?

SELECT subscription_status,
COUNT(customer_id) AS users,
ROUND(AVG(purchase_amount),2) AS avg_revenue,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer 
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Business Problem : The effectiveness of subscription programs is unknown.

-- Impact : Validates subscription model performance
		 -- Improves customer loyalty programs
         -- Increases customer lifetime value (CLV)

-- 8. Top 5 products with highest discount usage % 

SELECT item_purchased,
COUNT(item_purchased) AS total_number_of_sold,
COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) AS number_of_sold_discount_applied,
ROUND(COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*),2) AS discount_percent
FROM customer 
GROUP BY item_purchased
ORDER BY discount_percent DESC LIMIT 5;

-- Business Problem : Some products may be overly dependent on discounts.

-- Impact : Identifies discount-driven products
		 -- Helps optimize pricing strategy
         -- Reduces profit margin loss
         
-- 9. Segment customer into new , returning and loyal based on their total number 
-- of previous purchase and show the count of each segment.

SELECT 
	CASE
		WHEN previous_purchases = '0' THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
	ELSE 'Loyal Customers'
END AS customer_segment,
COUNT(*) AS customer_count FROM customer 
GROUP BY CASE
		WHEN previous_purchases = '0' THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
	ELSE 'Loyal Customers'
END;

-- Business Problem : Lack of customer segmentation leads to generic strategies.

-- Impact : Enables personalized marketing
		 -- Improves retention strategies
         -- Increases conversion rates

-- 10. What are the top 3 most purchased products within each category ?

WITH ranked_data AS (
    SELECT 
        category, 
        item_purchased,
        COUNT(item_purchased) AS most_purchased,
        RANK() OVER(
            PARTITION BY category 
            ORDER BY COUNT(item_purchased) DESC
        ) AS RNK
    FROM customer
    GROUP BY category, item_purchased
)
SELECT * FROM ranked_data
WHERE RNK <= 3;

-- Business Problem : The company doesn't know top-performing products within categories.

-- Impact : Improves product placement & reconnendations
		 -- Helps inventory optimazation
         -- Increases sales through best-sellers
         
-- 11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

SELECT 
	CASE
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Normal Buyers'
	END AS customer_type,
    subscription_status,
    COUNT(*) AS customer_count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY CASE
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Normal Buyers'
	END),2)
    AS percent
FROM customer 
GROUP BY CASE
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Normal Buyers'
	END, subscription_status;
-- 1047 

-- Business Problem : Unclear relationship between loyalty and subscription.

-- Impact : Improves subscription targeting
		 -- Increases conversion to paid programs 
         -- Increase customer retention strategy

-- 12. What is the revenue contribution of each age group ?

SELECT 
	CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
		WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
	END AS age_group,
    ROUND(SUM(purchase_amount),2) AS total_revenue 
FROM customer 
GROUP BY CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
		WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
	END
    ORDER BY total_revenue DESC;

-- Business Problem : No visibility into which age group contributes most to revenue

-- Impact : Enables age-base-targeting
		 -- Enhances marketing efficiency









